name: Webbuild


on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Godot Web
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.1
          use-dotnet: false

      - name: Export Web
        run: |
          mkdir -p docs
          godot --headless --export-release "build-web" docs/index.html

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated web build"
          file_pattern: docs/**